### ISSUE TITLE
default path for hasher-priv is invalid

### ISSUE THREAD

**Issue by yapavelkurochkin** [wolneykien/pocket#1]
Look at Pocketfile:
...
HSHPRIVDIR = /usr/libexec/hasher-priv
...

pk@sonic:~/src$ ls /usr/libexec/hasher-priv
ls: cannot access /usr/libexec/hasher-priv: No such file or directory

**Comment by wolneykien** [comment]
Yep. Set the correct one in `pocket.conf`. :-) You may also need to use `pocket-init -c <pocket.conf>` if the modified configuration file is located outside the pocket dir.
